/**
 * Icon Registry - Pure JavaScript whitelist of allowed lucide-react icons
 */

import {
  Home,
  Menu,
  X,
  Search,
  Settings,
  User,
  Users,
  Bell,
  Mail,
  Phone,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  Check,
  Plus,
  Minus,
  Edit,
  Trash,
  Eye,
  EyeOff,
  Copy,
  Share,
  Send,
  Download,
  Upload,
  AlertCircle,
  AlertTriangle,
  CheckCircle,
  XCircle,
  Info,
  HelpCircle,
  Facebook,
  Twitter,
  Instagram,
  Youtube,
  Linkedin,
  Github,
  Globe,
  Link,
  ExternalLink,
  ShoppingCart,
  CreditCard,
  DollarSign,
  TrendingUp,
  TrendingDown,
  BarChart,
  PieChart,
  File,
  Folder,
  Save,
  Print,
  Bookmark,
  Calendar,
  Clock,
  Tag,
  Flag,
  Image,
  Video,
  Camera,
  Music,
  Mic,
  Headphones,
  Volume,
  Play,
  Pause,
  Lock,
  Unlock,
  Shield,
  Database,
  Server,
  Cloud,
  Wifi,
  Battery,
  Monitor,
  Smartphone,
  Sun,
  Moon,
  Star,
  Heart,
  Zap,
  Target,
  Award,
  Trophy,
  Gift,
  Coffee,
  ArrowUpRight,
  Maximize2,
} from 'lucide-react'

export const ICON_REGISTRY = {
  'home': Home,
  'menu': Menu,
  'x': X,
  'search': Search,
  'settings': Settings,
  'user': User,
  'users': Users,
  'bell': Bell,
  'mail': Mail,
  'phone': Phone,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'chevron-down': ChevronDown,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'check': Check,
  'plus': Plus,
  'minus': Minus,
  'edit': Edit,
  'trash': Trash,
  'eye': Eye,
  'eye-off': EyeOff,
  'copy': Copy,
  'share': Share,
  'send': Send,
  'download': Download,
  'upload': Upload,
  'alert-circle': AlertCircle,
  'alert-triangle': AlertTriangle,
  'check-circle': CheckCircle,
  'x-circle': XCircle,
  'info': Info,
  'help-circle': HelpCircle,
  'facebook': Facebook,
  'twitter': Twitter,
  'instagram': Instagram,
  'youtube': Youtube,
  'linkedin': Linkedin,
  'github': Github,
  'globe': Globe,
  'link': Link,
  'external-link': ExternalLink,
  'shopping-cart': ShoppingCart,
  'credit-card': CreditCard,
  'dollar-sign': DollarSign,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  'bar-chart': BarChart,
  'pie-chart': PieChart,
  'file': File,
  'folder': Folder,
  'save': Save,
  'print': Print,
  'bookmark': Bookmark,
  'calendar': Calendar,
  'clock': Clock,
  'tag': Tag,
  'flag': Flag,
  'image': Image,
  'video': Video,
  'camera': Camera,
  'music': Music,
  'mic': Mic,
  'headphones': Headphones,
  'volume': Volume,
  'play': Play,
  'pause': Pause,
  'lock': Lock,
  'unlock': Unlock,
  'shield': Shield,
  'database': Database,
  'server': Server,
  'cloud': Cloud,
  'wifi': Wifi,
  'battery': Battery,
  'monitor': Monitor,
  'smartphone': Smartphone,
  'sun': Sun,
  'moon': Moon,
  'star': Star,
  'heart': Heart,
  'zap': Zap,
  'target': Target,
  'award': Award,
  'trophy': Trophy,
  'gift': Gift,
  'coffee': Coffee,
  'arrow-up-right': ArrowUpRight,
  'maximize-2': Maximize2,
}

export const getValidIconKeys = () => {
  return Object.keys(ICON_REGISTRY)
}

export const isValidIconKey = (key) => {
  return key in ICON_REGISTRY
}

export default ICON_REGISTRY